name: Container build - Push action
on:
  push:
      branches:
        - master
        - miesh

jobs:
  build-container:
    name: Build Backend and Frontend Containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Branch Names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v1.2

      - name: Build and push backend image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cenit-v2
          registry: ghcr.io
          tags: frontend-${{ steps.branch-name.outputs.current_branch }}-${{ steps.short-sha.outputs.sha }}
